### ISSUE TITLE
Trowel-1.2.1-1.19.2 Not Compatible With Latest Quilt Kotlin

### ISSUE THREAD

**Issue by RyanSalad** [theendercore/Trowel#5]
I was wanting to add Trowel 1.2.1 to a modpack because it's marked compatible with Quilt 1.19.2, but it won't accept the most up to date Quilt Kotlin Libraries for 1.19.2 which is 1.9.0+kotlin1.8.0. 

Trowel requires 1.9.4+kotlin1.8.21 which doesn't appear to be available in QKL at this point in time, so I wanted to let you know that this is an issue that I'm running into

**Comment by theendercore** [comment]
Okay, this is Fu%$ annoying. 

So, Fabric Language Kotlin, only ships Kotlin and some core libs.
Therefor it can be run on any version of fabric from 14 to 20.4.

BUT Quilt Kotlin Libraries does more than that, they ship extra things with their code, like things that really on minecraft versions. 

Which means I either have to go and downgrade the Kotlin version.
Or you can try and Install Fabric Language Kotlin, as long as nothing else needs QKL specifically it should work.

**Comment by RyanSalad** [comment]
Thank you for looking into it. I'll give installing Fabric Language Kotlin a try, and see what happens

**Comment by theendercore** [comment]
When I have time, ill try to get in contact with the quilt team and try to ask them to separate their Kotlin libs from the Kotlin runtime since, that way this is never a problem and older mods can use the new version of Kotlin, like they can in Fabric and Forge.

**Comment by RyanSalad** [comment]
> Or you can try and Install Fabric Language Kotlin, as long as nothing else needs QKL specifically it should work.

Hey sorry for the late reply. Time really got away from me. I had some quilt mods that specifically needed QKL so I was out of luck in terms of being able to just rely on Fabric Kotlin. Thank you for trying your hand at figuring this out btw
