### ISSUE TITLE
Forge 1.20.1 please?

### ISSUE THREAD

**Issue by KrokusAstra** [theendercore/Trowel#7]
Hi! You did good job, i like the mod! 
I just want to ask, if you plan to add forge support? It's useful thing for builders, i wish to had it on another modpack on forge.
Even if you decide not to do that, i wish you luck! Modders are cool!

**Comment by theendercore** [comment]
Nr. 1. Forge is dead, everyone now uses neo
Nr. 2. Have you heard of this funny little mod Quark? I heard it has a similar feature
Nr. 3. As much fun doing more work would be, I don't have time to like work on all the mods I'm working on rn.

But if you want this mod to be ported like in a day, just donate a couple of moneys to me on ko-fi and then ill get it's done in no time.
